### ISSUE TITLE
Would it be helpful to crossthrough/delete entries where the website no longer exists? 

### ISSUE THREAD

**Issue by chetaldrich** [HackathonHackers/personal-sites#194]
It's just been somewhat annoying if I come by and click on quite a few links and find that there's no longer a website at the URL.

**Comment by bryangarza** [comment]
We can check them all together with https://github.com/bamos/girl.

**Comment by chetaldrich** [comment]
Cool it looks like you guys are on it. Thanks!

**Comment by iangcarroll** [comment]
Will close this issue once I check the other ~850 links.

**Comment by iangcarroll** [comment]
#206 closes this.
