### ISSUE TITLE
Separate markdown files for different profiles

### ISSUE THREAD

**Issue by cassidoo** [HackathonHackers/personal-sites#212]
What if we had one README for personal websites, one for GitHub repos, one for LinkedIn profiles, etc?  It'd make for less scrolling.

**Comment by iangcarroll** [comment]
Yeah, we should split it up. Although, if we intend on creating many more categories like LinkedIn, we might want to create a website with profiles or something more easily navigable.

**Comment by bryangarza** [comment]
Maybe we should convert to JSON.

**Comment by iangcarroll** [comment]
and then generate markdown files from there?

**Comment by bryangarza** [comment]
And then generate a github-pages site.

**Comment by robbyoconnor** [comment]
:+1:

**Comment by iangcarroll** [comment]
Does anyone want to take this on?

**Comment by cassidoo** [comment]
Sure thing. :)
