### ISSUE TITLE
Dead/Spammy Links

### ISSUE THREAD

**Issue by dingwilson** [HackathonHackers/personal-sites#602]
Are there any plans to remove dead or spammy links? For example, Frank Cash's website does not work, and Emily Tran's website leads to a spam site for me.

**Comment by iangcarroll** [comment]
If you see any spammy links, just file an issue; I removed Emily Tran's website from the list and messaged her. 

I'll ask Frank Cash about his site. I believe we used a tool in the past to purge dead domains, and we might want to use that again.

**Comment by dingwilson** [comment]
Achal Varma's website doesn't actually show anything aside from a generic "parked website" page.

**Comment by dingwilson** [comment]
Matthew Bucci's website is down

**Comment by dingwilson** [comment]
Su Min Kim's website is down

**Comment by binhonglee** [comment]
Checked all the personal websites and just made a pull request #633 to address this issue.

**Comment by KevCron** [comment]
More websites that are down for me:

- [Aaron Dancer](http://aarondancer.com/)
- [Aayush Ranaut](http://aayush.net)
- [Abhinav Rajaseshan](http://abhiseshan.me/)
- [Achal Varma](http://acha.lv/)

I'll just add more as I find them.

**Comment by JoshuaRLi** [comment]
Surprised no one has created a CI hook/script to probe non-200 response codes for the URLs.

**Comment by binhonglee** [comment]
@JoshuaRLi My pull request took them 1 year to respond to. I don't think they are even trying anymore.

**Comment by dingwilson** [comment]
Something like this might be cool: https://github.com/dkhamsing/awesome_bot

I know this is currently being used to check for dead links/redirections in several website list repos. It can be integrated with TravisCI, CircleCI, Danger, etc.

**Comment by dingwilson** [comment]
Seems this org doesn't really care about this. Closing...
